### ISSUE TITLE
Enable metrics to support updated MAO metrics integration

### ISSUE THREAD

**Issue by Danil-Grigorev** [openshift/cluster-api-provider-openstack#100]
/kind feature

With recent enablement of metrics (openshift/machine-api-operator#609) it would now rely on an assumption the metrics will be served on port `8083` for the `machine-controller`. This would require to revendor the MAO and enable metrics serving in controller-runtime manager instance.

[A clear and concise description of what you want to happen.]

Expose port `8081` and wire it to metrics serving.

**Anything else you would like to add:**

Example implementation: https://github.com/openshift/cluster-api-provider-aws/pull/324

[Miscellaneous information that will assist in solving the issue.]

**Comment by pierreprinetti** [comment]
(internally tracked with id OSASINFRA-1774)
