### ISSUE TITLE
[Question] How does OCP consuming this provider

### ISSUE THREAD

**Issue by gyliu513** [openshift/cluster-api-provider-openstack#71]
Hi, may I know how does OCP is consuming this cloud provider? Can anyone show some detail for this?

I found openshift forked all of the cloud providers based on cluster api, hope to get some detail for how those cloud providers are being consumed, thanks!

FYI @enxebre

**Comment by gyliu513** [comment]
@tomassedovic so you mean that OCP installer only consumes the `cluster-api-provider-openstack` machine API part? Can you please show me some code snippet in installer, that would helps :)

**Comment by tomassedovic** [comment]
@gyliu513 I'm sorry for the delay.

Yes, OpenShift deployed by the installer only consumes the Machine API part of cluster-api-provider-openstack.

This is not an area I'm super strong on, but here's what I know: https://github.com/openshift/installer/tree/master/pkg/asset/machines/openstack

After that, it doesn't have much more to do with cluster-api-provider-openstack. The actual container and the necessary resource definitions are created by machine-api-operator:

https://github.com/openshift/machine-api-operator

E.g. this defines the image URLs that the operator can use:

https://github.com/openshift/machine-api-operator/blob/master/install/0000_30_machine-api-operator_01_images.configmap.yaml

I believe it is the machine-api-operator which spawns the CAPO machine API container. But I am not a 100% sure of that. I am also not sure which component starts the machine-api-operator itself.

@enxebre might be able to fill in the gaps.

**Comment by gyliu513** [comment]
Thanks @tomassedovic , same as my understanding. :)

@enxebre Look forward to more detail from you.
